// fichier comportant toutes les langues possible et toutes les voix associer à chaque langues

export const langs_codes = {
    'Arabic (Egypt)': 'ar-eg',
    'Arabic (Saudi Arabia)': 'ar-sa',
    'Bulgarian': 'bg-bg',
    'Catalan': 'ca-es',
    'Chinese (China)': 'zh-cn',
    'Chinese (Hong Kong)': 'zh-hk',
    'Chinese (Taiwan)': 'zh-tw',
    'Croatian': 'hr-hr',
    'Czech': 'cs-cz',
    'Danish': 'da-dk',
    'Dutch (Belgium)': 'nl-be',
    'Dutch (Netherlands)': 'nl-nl',
    'English (Australia)': 'en-au',
    'English (Canada)': 'en-ca',
    'English (Great Britain)': 'en-gb',
    'English (India)': 'en-in',
    'English (Ireland)': 'en-ie',
    'English (United States)': 'en-us',
    'Finnish': 'fi-fi',
    'French (Canada)': 'fr-ca',
    'French (France)': 'fr-fr',
    'French (Switzerland)': 'fr-ch',
    'German (Austria)': 'de-at',
    'German (Germany)': 'de-de',
    'German (Switzerland)': 'de-ch',
    'Greek': 'el-gr',
    'Hebrew': 'he-il',
    'Hindi': 'hi-in',
    'Hungarian': 'hu-hu',
    'Indonesian': 'id-id',
    'Italian': 'it-it',
    'Japanese': 'ja-jp',
    'Korean': 'ko-kr',
    'Malay': 'ms-my',
    'Norwegian': 'nb-no',
    'Polish': 'pl-pl',
    'Portuguese (Brazil)': 'pt-br',
    'Portuguese (Portugal)': 'pt-pt',
    'Romanian': 'ro-ro',
    'Russian': 'ru-ru',
    'Slovak': 'sk-sk',
    'Slovenian': 'sl-si',
    'Spanish (Mexico)': 'es-mx',
    'Spanish (Spain)': 'es-es',
    'Swedish': 'sv-se',
    'Tamil': 'ta-in',
    'Thai': 'th-th',
    'Turkish': 'tr-tr',
    'Vietnamese': 'vi-vn'
  }

export const voices = {
    'ar-eg': ['Oda (Female)'],
    'ar-sa': ['Salim (Male)'],
    'bg-bg': ['Dimo (Male)'],
    'ca-es': ['Rut (Female)'],
    'zh-cn': ['Luli (Female)', 'Shu (Female)', 'Chow (Female)', 'Wang (Male)'],
    'zh-hk': ['Jia (Female)', 'Xia (Female)', 'Chen (Male)'],
    'zh-tw': ['Akemi (Female)', 'Lin (Female)', 'Lee (Male)'],
    'hr-hr': ['Nikola (Male)'],
    'cs-cz': ['Josef (Male)'],
    'da-dk': ['Freja (Female)'],
    'nl-be': ['Daan (Male)'],
    'nl-nl': ['Lotte (Female)', 'Bram (Male)'],
    'en-au': ['Zoe (Female)', 'Isla (Female)', 'Evie (Female)', 'Jack (Male)'],
    'en-ca': ['Rose (Female)', 'Clara (Female)', 'Emma (Female)', 'Mason (Male)'],
    'en-gb': ['Alice (Female)', 'Nancy (Female)', 'Lily (Female)', 'Harry (Male)'],
    'en-in': ['Eka (Female)', 'Jai (Female)', 'Ajit (Male)'],
    'en-ie': ['Oran (Male)'],
    'en-us': ['Linda (Female)', 'Amy (Female)', 'Mary (Female)', 'John (Male)', 'Mike (Male)'],
    'fi-fi': ['Aada (Female)'],
    'fr-ca': ['Emile (Female)', 'Olivia (Female)', 'Logan (Female)', 'Felix (Male)'],
    'fr-fr': ['Bette (Female)', 'Iva (Female)', 'Zola (Female)', 'Axel (Male)'],
    'fr-ch': ['Theo (Male)'],
    'de-at': ['Lukas (Male)'],
    'de-de': ['Hanna (Female)', 'Lina (Female)', 'Jonas (Male)'],
    'de-ch': ['Tim (Male)'],
    'el-gr': ['Neo (Male)'],
    'he-il': ['Rami (Male)'],
    'hi-in': ['Puja (Female)', 'Kabir (Male)'],
    'hu-hu': ['Mate (Male)'],
    'id-id': ['Intan (Male)'],
    'it-it': ['Bria (Female)', 'Mia (Female)', 'Pietro (Male)'],
    'ja-jp': ['Hina (Female)', 'Airi (Female)', 'Fumi (Female)', 'Akira (Male)'],
    'ko-kr': ['Nari (Female)'],
    'ms-my': ['Aqil (Male)'],
    'nb-no': ['Marte (Female)', 'Erik (Male)'],
    'pl-pl': ['Julia (Female)', 'Jan (Male)'],
    'pt-br': ['Marcia (Female)', 'Ligia (Female)', 'Yara (Female)', 'Dinis (Male)', 'Leonor (Female)'],
    'ro-ro': ['Doru (Male)'],
    'ru-ru': ['Olga (Female)', 'Marina (Female)', 'Peter (Male)'],
    'sk-sk': ['Beda (Male)'],
    'sl-si': ['Vid (Male)'],
    'es-mx': [ 'Juana (Female)', 'Silvia (Female)', 'Teresa (Female)', 'Jose (Male)'],
    'es-es': ['Camila (Female)', 'Sofia (Female)', 'Luna (Female)', 'Diego (Male)'],
    'sv-se': ['Molly (Female)', 'Hugo (Male)'],
    'ta-in': ['Sai (Male)'],
    'th-th': ['Ukrit (Male)'],
    'tr-tr': ['Omer (Male)'],
    'vi-vn': ['Chi (Male)'],
}
